// note this entire script is AI generated by gemini

const triggerBtn = document.getElementById('trigger-btn');
const container = document.getElementById('toast-container');
let count = 0;

const MAX_TOASTS = 3;
const TOAST_GAP = 12; // Match CSS gap spacing

const toastTypes = {
  success: { text: "Success! Action complete.", className: "toast-success" },
  error: { text: "Error! Something failed. This text is long on purpose to show off the dynamic variable text wrap heights resizing without breaking layout code grids.", className: "toast-error" },
  warn: { text: "Warning! Check settings.", className: "toast-warn" }
};

function updateToastPositions() {
  const activeToasts = Array.from(container.querySelectorAll('.toast-item:not(.toast-exiting)'));

  let currentRunningOffset = 0;

  // Calculate from bottom up (oldest to newest reversed)
  activeToasts.reverse().forEach((toast) => {
    toast.style.setProperty('--toast-offset', `${currentRunningOffset}px`);

    // Add this specific element's layout footprint height + gap space to the stack height total
    const measuredHeight = toast.getBoundingClientRect().height;
    currentRunningOffset += measuredHeight + TOAST_GAP;
  });
}

triggerBtn.addEventListener('click', () => {
  count++;

  const activeToasts = Array.from(container.querySelectorAll('.toast-item:not(.toast-exiting)'));

  if (activeToasts.length >= MAX_TOASTS) {
    const oldestToast = activeToasts[0];

    // Calculate precise 4th slot height override dynamically based on its own measured bound box size
    const currentOffset = parseInt(oldestToast.style.getPropertyValue('--toast-offset') || '0');
    const toastHeight = oldestToast.getBoundingClientRect().height;
    const forcedExitOffset = currentOffset + toastHeight + TOAST_GAP;

    oldestToast.style.setProperty('--toast-offset', `${forcedExitOffset}px`);
    oldestToast.classList.add('toast-exiting');

    oldestToast.addEventListener('animationend', (e) => {
      if (e.animationName === 'toast-exit-forced') {
        oldestToast.hidePopover();
        oldestToast.remove();
      }
    });
  }

  const types = Object.keys(toastTypes);
  const selectedType = types[count % types.length];
  const config = toastTypes[selectedType];

  const toast = document.createElement('div');
  toast.setAttribute('popover', 'manual');
  toast.className = `toast-item ${config.className}`;
  const toastId = `toast-${count}`;
  toast.id = toastId;

  toast.innerHTML = `
    <span class="toast-icon"></span>
    <span class="toast-message">${config.text} (#${count})</span>
    <button popovertarget="${toastId}" popovertargetaction="hide" class="toast-close-btn">&times;</button>
    <div class="progress-bar"></div>
  `;

  container.appendChild(toast);
  toast.showPopover();

  // Measure and reposition everything now that the element exists in the DOM tree
  updateToastPositions();

  const duration = 4000;
  let startTime = Date.now();
  let remainingTime = duration;
  let dismissTimeout;

  const startTimer = () => {
    startTime = Date.now();
    dismissTimeout = setTimeout(() => {
      toast.hidePopover();
    }, remainingTime);
  };

  const pauseTimer = () => {
    clearTimeout(dismissTimeout);
    remainingTime -= Date.now() - startTime;
  };

  toast.addEventListener('toggle', (event) => {
    if (event.newState === 'closed') {
      clearTimeout(dismissTimeout);
      toast.remove();
      updateToastPositions(); // Recalculate remaining heights smoothly
    }
  });

  toast.addEventListener('mouseenter', () => {
    if (!toast.classList.contains('toast-exiting')) pauseTimer();
  });
  toast.addEventListener('mouseleave', () => {
    if (!toast.classList.contains('toast-exiting')) startTimer();
  });

  startTimer();
});
